services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        VITE_API_URL: http://http://localhost:3000/

    container_name: frontend-container

    # Maps host's 8080 port to the container's 8080 listening port
    ports:
      - "8080:8080"

    image: my-frontend-app:v1.0.0
    restart: always
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend-container
    volumes:
      - ./backend:/var/www/html
      - /var/www/html/node_modules
    ports:
      - "3000:3000"
    restart: always
